---
# Deployment for MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ascn-cluster
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      volumes: 
      - name: ghost-pv
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql:latest
        env: # The variables below could be set on a ConfigMap object
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: ghost
        - name: MYSQL_USER
          value: ghostuser
        - name: MYSQL_PASSWORD
          value: pass # Use Secret object in real usage
        ports:
        - containerPort: 3306
