apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ghost-storage-class
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none


