- name: create k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1 
      kind: namespace
      metadata:
        name: ascn-cluster

- name: Mysql Persistent Volume Claim
  kubernetes.core.k8s:
    state: present
    src: ../k8s/mysql-pvc.yml

- name: database service
  kubernetes.core.k8s:
    state: present
    src: ../k8s/mysql-service.yml

- name:  database deployment 
  kubernetes.core.k8s:
    state: present
    src: ../k8s/mysql-deployment.yml
  
- name: create storage class 
  kubernetes.core.k8s:
    state: present
    src: ../k8s/storage-class.yml
