---


# deveriamos lancar um namespace antes??
# - name: Create k8s pod for ghost app  
  # kubernetes.core.k8s:    
    # state: present    
    # definition:      
      # apiVersion: v1      
      # kind: Pod      
      # metadata:        
        # name: "{{ app }}"        
        # namespace: {{ namespace }}      
        # labels:          
          # app: "{{ app }}"      
      # spec:        
      #   containers:          
      #     - name: "{{ app }}"            
      #       image: "{{ image }}"            
      #       imagePullPolicy: Always


#SOURCES:
# https://blog.wuhsun.com/migrate-ghost-blog-from-aws-ec2-to-gcp-gke/
# https://bitnami.com/stack/ghost/helm
# https://github.com/bitnami/charts/blob/main/bitnami/ghost/values.yaml
- name: Add a ghost repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami


- name: Deploy latest version of ghost
  kubernetes.core.helm:
    name: my-release
    chart_ref: bitnami/ghost
    release_namespace: "{{namespace}}"
    create_namespace: true
    values:
      service:
        type: LoadBalancer
        httpsPort: 443
      postgresql:
        replication:
          enabled: true